apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  MONGODB_URI: {{ .Values.database.url | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | b64enc }}
  AWS_SESSION_TOKEN: {{ .Values.aws.sessionToken | b64enc }}
  AWS_REGION: {{ .Values.aws.region | b64enc }}