replicaCount: 2

image:
  repository: localhost:5000/mazyfood-payment
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8082
  targetPort: 8082

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50

database:
  url: mongodb://host.minikube.internal:27017/payment
